// Plain-text formatters for /clanreport. Each `format*` function returns
// the panel body (without the metadata header or shared KPI block, which
// are emitted separately by `buildMetadataHeader` and `buildKpiBlock`).
//
// Tables are aligned with fixed-width columns padded with spaces.

import { getWindow } from './panelRegistry.js';

const SEP = '='.repeat(73);
const HR  = '-'.repeat(73);

// ── Primitives ──────────────────────────────────────────────────

function pad(str, width, align = 'left') {
  const s = String(str ?? '');
  if (s.length >= width) return s.slice(0, width);
  const fill = ' '.repeat(width - s.length);
  return align === 'right' ? fill + s : s + fill;
}

function hours(seconds) {
  return ((Number(seconds) || 0) / 3600).toFixed(1);
}

function num(n) {
  return Number(n || 0).toLocaleString('en-US');
}

function pct(part, total) {
  const p = Number(part) || 0;
  const t = Number(total) || 0;
  if (t === 0) return '0';
  return ((p / t) * 100).toFixed(0);
}

function fmtDate(d) {
  if (!d) return 'never';
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return 'never';
  const Y = date.getUTCFullYear();
  const M = String(date.getUTCMonth() + 1).padStart(2, '0');
  const D = String(date.getUTCDate()).padStart(2, '0');
  const h = String(date.getUTCHours()).padStart(2, '0');
  const m = String(date.getUTCMinutes()).padStart(2, '0');
  return `${Y}-${M}-${D} ${h}:${m}`;
}

function fmtDateOnly(d) {
  if (!d) return 'never';
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return 'never';
  return date.toISOString().slice(0, 10);
}

function daysAgo(d) {
  if (!d) return null;
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return null;
  const ms = Date.now() - date.getTime();
  return Math.floor(ms / 86400000);
}

function truncateName(s, w = 28) {
  const n = String(s ?? '');
  return n.length <= w ? n : n.slice(0, w - 1) + '~';
}

// ── Metadata header & KPI block ─────────────────────────────────

export function buildMetadataHeader({ panel, panelLabel, clan, server, window, generatedBy, botVersion }) {
  const win = getWindow(window);
  const now = new Date();
  let windowLine;
  if (win.days === null) {
    windowLine = 'All time';
  } else {
    const start = new Date(now.getTime() - win.days * 86400000);
    windowLine = `Last ${win.days} days (${fmtDateOnly(start)} to ${fmtDateOnly(now)} UTC)`;
  }
  const lines = [
    SEP,
    'Royal Battalion - Clan Report',
    SEP,
    `Report:        ${panelLabel}`,
    `Clan:          [${clan.tag}] ${clan.name} (id: ${clan.id})`,
    `Server:        ${server.name} (id: ${server.id})`,
    `Time window:   ${windowLine}`,
    `Generated:     ${fmtDate(now)} UTC`,
    `Generated by:  @${generatedBy.tag || generatedBy.username} (Discord ID: ${generatedBy.id})`,
    `Bot version:   ${botVersion}`,
    SEP,
    '',
  ];
  return lines.join('\n');
}

export function buildKpiBlock(kpi, clanTag, windowId) {
  const win = getWindow(windowId);
  const windowNote = win.days === null ? 'all time' : `last ${win.days} days`;
  const lines = [
    `SUMMARY (${windowNote} unless noted)`,
    HR,
    `Whitelisted members:   ${num(kpi.activeMembers)} active (${num(kpi.expiringSoon)} expiring within 14d)`,
    `Hours played:          ${hours(kpi.totalSessionSeconds)} h  (avg ${kpi.activeMembers ? (Number(kpi.totalSessionSeconds) / 3600 / kpi.activeMembers).toFixed(1) : '0.0'} h/member)`,
    `Seed hours:            ${hours(kpi.totalSeedSeconds)} h  (${pct(kpi.totalSeedSeconds, kpi.totalSessionSeconds)}% of total)`,
    `Combat:                Kills ${num(kpi.kills)} / Deaths ${num(kpi.deaths)} (K/D ${(kpi.kills / Math.max(kpi.deaths, 1)).toFixed(2)})`,
    `Match win rate:        ${kpi.matchesCounted ? `${pct(kpi.wins, kpi.matchesCounted)}% over ${num(kpi.matchesCounted)} matches w/ >=1 member` : 'no matches recorded'}`,
    `Last activity:         ${kpi.lastActivity ? `${fmtDate(kpi.lastActivity.lastSeen)} UTC (${kpi.lastActivity.name || '?'})` : 'never'}`,
    `Tag spotters:          ${num(kpi.tagSpottersCount)} in-game [${clanTag}] tags not whitelisted (last 30d)`,
    '',
  ];
  return lines.join('\n');
}

// ── Panel bodies ────────────────────────────────────────────────

export function formatOverview({ tagSpotters, clan, windowId }) {
  const win = getWindow(windowId);
  const winNote = win.days === null ? 'all time' : `last ${win.days}d`;
  const lines = [
    `TAG SPOTTERS - ${tagSpotters.length} in-game [${clan.tag}] wearers not whitelisted (last 30d)`,
    HR,
    `${pad('Name', 28)}| ${pad('SteamID', 18)}| ${pad('Last seen (UTC)', 18)}| Hours ${winNote}`,
  ];
  if (tagSpotters.length === 0) {
    lines.push('(none)');
  } else {
    for (const r of tagSpotters) {
      lines.push(
        `${pad(truncateName(r.name), 28)}| ${pad(r.steamId, 18)}| ${pad(fmtDate(r.lastSeen), 18)}| ${pad(hours(r.totalSeconds), 6, 'right')}`
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function formatActivity({ rows, members, lastSeenMap }) {
  // Left-join: include whitelist members with no SquadJS rows
  const byId = new Map(rows.map((r) => [r.steamId, r]));
  const merged = members.map((m) => {
    const r = byId.get(m.steamId);
    const ls = lastSeenMap.get(m.steamId);
    return {
      steamId: m.steamId,
      name: (r?.name) || m.name || ls?.name || '?',
      lastSeen: r?.lastSeen || ls?.lastSeen || null,
      totalSeconds: Number(r?.totalSeconds || 0),
      seedSeconds: Number(r?.seedSeconds || 0),
      seedSessions: Number(r?.seedSessions || 0),
      joinCount: Number(r?.joinCount || 0),
    };
  }).sort((a, b) => b.totalSeconds - a.totalSeconds);

  const lines = [
    'ACTIVITY - sorted by hours descending',
    HR,
    `${pad('Name', 22)}| ${pad('SteamID', 18)}| ${pad('Last seen (UTC)', 18)}| ${pad('Hours', 7, 'right')} | ${pad('Seed h', 6, 'right')} | ${pad('Seed#', 5, 'right')} | Joins`,
  ];
  if (merged.length === 0) {
    lines.push('No members found.');
  } else {
    let tH = 0, tS = 0, tSS = 0, tJ = 0;
    for (const r of merged) {
      tH += r.totalSeconds;
      tS += r.seedSeconds;
      tSS += r.seedSessions;
      tJ += r.joinCount;
      lines.push(
        `${pad(truncateName(r.name, 22), 22)}| ${pad(r.steamId, 18)}| ${pad(fmtDate(r.lastSeen), 18)}| ${pad(hours(r.totalSeconds), 7, 'right')} | ${pad(hours(r.seedSeconds), 6, 'right')} | ${pad(String(r.seedSessions), 5, 'right')} | ${r.joinCount}`
      );
    }
    lines.push(HR);
    lines.push(
      `${pad('TOTAL', 22)}| ${pad('', 18)}| ${pad('', 18)}| ${pad(hours(tH), 7, 'right')} | ${pad(hours(tS), 6, 'right')} | ${pad(String(tSS), 5, 'right')} | ${tJ}`
    );
  }
  lines.push('');
  return lines.join('\n');
}

export function formatSeeding({ rows, members, milestoneTarget }) {
  const byId = new Map(rows.map((r) => [r.steamId, r]));
  const merged = members.map((m) => {
    const r = byId.get(m.steamId);
    return {
      steamId: m.steamId,
      name: r?.name || m.name || '?',
      seedDays: Number(r?.seedDays || 0),
      seedSeconds: Number(r?.seedSeconds || 0),
      avgQuality: r?.avgQuality !== null && r?.avgQuality !== undefined ? Number(r.avgQuality) : null,
      thresholdSessions: Number(r?.thresholdSessions || 0),
      lastSeedDate: r?.lastSeedDate || null,
    };
  }).sort((a, b) => b.seedDays - a.seedDays || b.seedSeconds - a.seedSeconds);

  const lines = [
    'SEEDING - sorted by unique seed days descending',
    HR,
    `${pad('Name', 22)}| ${pad('Seed days', 9, 'right')} | ${pad('Seed h', 6, 'right')} | ${pad('Avg qual', 8, 'right')} | ${pad('Thresh', 6, 'right')} | Last seed`,
  ];
  if (merged.length === 0) {
    lines.push('No seed sessions recorded.');
  } else {
    for (const r of merged) {
      const q = r.avgQuality === null ? '-' : r.avgQuality.toFixed(2);
      lines.push(
        `${pad(truncateName(r.name, 22), 22)}| ${pad(String(r.seedDays), 9, 'right')} | ${pad(hours(r.seedSeconds), 6, 'right')} | ${pad(q, 8, 'right')} | ${pad(String(r.thresholdSessions), 6, 'right')} | ${fmtDateOnly(r.lastSeedDate)}`
      );
    }
  }

  if (milestoneTarget && Number(milestoneTarget) > 0) {
    const target = Number(milestoneTarget);
    const watch = merged.filter((r) => r.seedDays >= target - 2 && r.seedDays < target);
    lines.push('');
    lines.push(`MILESTONE WATCH (requiredSeedDays = ${target})`);
    if (watch.length === 0) {
      lines.push('(none within 2 days of threshold)');
    } else {
      lines.push(`${watch.length} member(s) between ${target - 2} and ${target - 1} seed days:`);
      for (const r of watch) {
        lines.push(`  - ${r.name} (${r.seedDays}/${target})`);
      }
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function formatRoster({ members, lastSeenMap }) {
  const lines = [
    'ROSTER - current whitelist (not affected by time window)',
    HR,
    `${pad('Role', 14)}| ${pad('Name', 24)}| ${pad('SteamID', 18)}| ${pad('Added', 12)}| ${pad('Expires', 12)}| Last seen`,
  ];
  if (members.length === 0) {
    lines.push('No members.');
  } else {
    for (const m of members) {
      const ls = lastSeenMap.get(m.steamId);
      lines.push(
        `${pad(truncateName(m.role || '?', 14), 14)}| ${pad(truncateName(m.name || '?', 24), 24)}| ${pad(m.steamId, 18)}| ${pad(fmtDateOnly(m.createdAt), 12)}| ${pad(m.expiresAt ? fmtDateOnly(m.expiresAt) : 'permanent', 12)}| ${fmtDateOnly(ls?.lastSeen)}`
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function formatCombat({ rows, members }) {
  const byId = new Map(rows.map((r) => [r.steamId, r]));
  const merged = members.map((m) => {
    const r = byId.get(m.steamId);
    return {
      steamId: m.steamId,
      name: r?.name || m.name || '?',
      kills: Number(r?.kills || 0),
      deaths: Number(r?.deaths || 0),
      teamkillsGiven: Number(r?.teamkillsGiven || 0),
      teamkillsTaken: Number(r?.teamkillsTaken || 0),
      revives: Number(r?.revives || 0),
      wounds: Number(r?.wounds || 0),
    };
  }).sort((a, b) => b.kills - a.kills);

  const lines = [
    'COMBAT - sorted by kills descending',
    HR,
    `${pad('Name', 22)}| ${pad('Kills', 6, 'right')} | ${pad('Deaths', 6, 'right')} | ${pad('K/D', 5, 'right')} | ${pad('TK Giv', 6, 'right')} | ${pad('TK Tkn', 6, 'right')} | ${pad('Revive', 6, 'right')} | Wounds`,
  ];
  if (merged.length === 0) {
    lines.push('No combat events recorded.');
  } else {
    let tK = 0, tD = 0, tTG = 0, tTT = 0, tR = 0, tW = 0;
    for (const r of merged) {
      tK += r.kills; tD += r.deaths; tTG += r.teamkillsGiven;
      tTT += r.teamkillsTaken; tR += r.revives; tW += r.wounds;
      const kd = (r.kills / Math.max(r.deaths, 1)).toFixed(2);
      lines.push(
        `${pad(truncateName(r.name, 22), 22)}| ${pad(String(r.kills), 6, 'right')} | ${pad(String(r.deaths), 6, 'right')} | ${pad(kd, 5, 'right')} | ${pad(String(r.teamkillsGiven), 6, 'right')} | ${pad(String(r.teamkillsTaken), 6, 'right')} | ${pad(String(r.revives), 6, 'right')} | ${r.wounds}`
      );
    }
    lines.push(HR);
    const totKd = (tK / Math.max(tD, 1)).toFixed(2);
    lines.push(
      `${pad('TOTAL', 22)}| ${pad(String(tK), 6, 'right')} | ${pad(String(tD), 6, 'right')} | ${pad(totKd, 5, 'right')} | ${pad(String(tTG), 6, 'right')} | ${pad(String(tTT), 6, 'right')} | ${pad(String(tR), 6, 'right')} | ${tW}`
    );
  }
  lines.push('');
  return lines.join('\n');
}

export function formatMatches({ perMember, matches }) {
  // Compute win attribution: clan plurality team vs winner.team_id
  let wins = 0, losses = 0, mixed = 0;
  let totalLengthMs = 0, lengthSamples = 0;
  let teamATot = 0, teamBTot = 0;
  const layerCounts = new Map();

  for (const m of matches) {
    if (m.layer) layerCounts.set(m.layer, (layerCounts.get(m.layer) || 0) + 1);
    if (m.start_time && m.end_time) {
      const ms = new Date(m.end_time).getTime() - new Date(m.start_time).getTime();
      if (ms > 0) { totalLengthMs += ms; lengthSamples++; }
    }
    // Plurality of clan team
    const teamIds = String(m.clanTeamIds || '').split(',').filter(Boolean).map(Number);
    let a = 0, b = 0;
    for (const t of teamIds) { if (t === 1) a++; else if (t === 2) b++; }
    teamATot += a;
    teamBTot += b;
    let clanTeam = null;
    if (a > b) clanTeam = 1;
    else if (b > a) clanTeam = 2;
    let winnerTeam = null;
    if (m.winner) {
      try {
        const parsed = typeof m.winner === 'string' ? JSON.parse(m.winner) : m.winner;
        if (parsed && (parsed.team_id || parsed.team)) {
          winnerTeam = Number(parsed.team_id || parsed.team);
        }
      } catch { /* ignore winner parse errors */ }
    }
    if (clanTeam === null) mixed++;
    else if (winnerTeam === null) { /* unknown outcome, skip */ }
    else if (clanTeam === winnerTeam) wins++;
    else losses++;
  }
  const counted = wins + losses;
  const winPct = counted ? Math.round((wins / counted) * 100) : 0;
  const avgLenMin = lengthSamples ? Math.round(totalLengthMs / lengthSamples / 60000) : 0;
  const factionTotal = teamATot + teamBTot;
  const teamAPct = factionTotal ? Math.round((teamATot / factionTotal) * 100) : 0;
  const teamBPct = factionTotal ? 100 - teamAPct : 0;

  const topLayers = [...layerCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const lines = [
    'MATCH OUTCOMES',
    HR,
    `Matches played (>=1 clan member):  ${num(matches.length)}`,
    `Wins:                              ${num(wins)} (${winPct}% of ${counted} decided)`,
    `Losses:                            ${num(losses)}`,
    `Mixed-team matches (excluded):     ${num(mixed)}`,
    `Avg match length:                  ${avgLenMin}m`,
    `Faction preference:                Team A ${teamAPct}% / Team B ${teamBPct}%`,
    '',
  ];
  if (topLayers.length > 0) {
    lines.push('TOP MAPS PLAYED');
    topLayers.forEach(([layer, c], i) => lines.push(`${i + 1}. ${layer} - ${c} matches`));
    lines.push('');
  }
  lines.push('PER-MEMBER PARTICIPATION');
  lines.push(`${pad('Name', 24)}| ${pad('Matches', 8, 'right')} | ${pad('Team A', 7, 'right')} | Team B`);
  if (perMember.length === 0) {
    lines.push('No participation recorded.');
  } else {
    for (const r of perMember) {
      lines.push(
        `${pad(truncateName(r.name || '?', 24), 24)}| ${pad(String(r.matchesPlayed), 8, 'right')} | ${pad(String(r.teamACount), 7, 'right')} | ${r.teamBCount}`
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function formatHeatmap({ hours: hourBuckets, dows }) {
  const lines = [];
  // Hour-of-day chart
  lines.push('HOUR-OF-DAY (UTC) - sessions started');
  lines.push(HR);
  const hMap = new Map(hourBuckets.map((r) => [Number(r.hour), Number(r.sessions)]));
  const hourValues = Array.from({ length: 24 }, (_, h) => hMap.get(h) || 0);
  const hMax = Math.max(...hourValues, 1);
  for (let h = 0; h < 24; h++) {
    const v = hourValues[h];
    const filled = Math.round((v / hMax) * 30);
    const bar = '#'.repeat(filled);
    lines.push(`${String(h).padStart(2, '0')} |${pad(bar, 30)} (${v})`);
  }
  lines.push('');

  // Day-of-week chart (MySQL DAYOFWEEK: 1=Sun, 2=Mon, ..., 7=Sat)
  lines.push('DAY-OF-WEEK');
  lines.push(HR);
  const dowMap = new Map(dows.map((r) => [Number(r.dow), Number(r.sessions)]));
  const dowLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const dowValues = dowLabels.map((_, i) => dowMap.get(i + 1) || 0);
  const dMax = Math.max(...dowValues, 1);
  for (let i = 0; i < 7; i++) {
    const v = dowValues[i];
    const filled = Math.round((v / dMax) * 30);
    const bar = '#'.repeat(filled);
    lines.push(`${dowLabels[i]} |${pad(bar, 30)} (${v})`);
  }
  lines.push('');
  return lines.join('\n');
}

export function formatGrowth({ newMembers, expired, inactive, windowId }) {
  const win = getWindow(windowId);
  const windowNote = win.days === null ? 'all time' : `last ${win.days} days`;
  const lines = [
    `GROWTH & CHURN (window: ${windowNote})`,
    HR,
    '',
    `NEW MEMBERS (${newMembers.length})`,
    `${pad('Name', 24)}| ${pad('Role', 14)}| ${pad('Added (UTC)', 12)}| SteamID`,
  ];
  if (newMembers.length === 0) lines.push('(none)');
  else for (const r of newMembers) {
    lines.push(`${pad(truncateName(r.name || '?', 24), 24)}| ${pad(truncateName(r.role || '?', 14), 14)}| ${pad(fmtDateOnly(r.createdAt), 12)}| ${r.steamId}`);
  }
  lines.push('');

  lines.push(`EXPIRED / REMOVED (${expired.length})`);
  lines.push(`${pad('Name', 24)}| ${pad('Role', 14)}| ${pad('Expired (UTC)', 14)}| SteamID`);
  if (expired.length === 0) lines.push('(none)');
  else for (const r of expired) {
    lines.push(`${pad(truncateName(r.name || '?', 24), 24)}| ${pad(truncateName(r.role || '?', 14), 14)}| ${pad(fmtDateOnly(r.expiresAt), 14)}| ${r.steamId}`);
  }
  lines.push('');

  lines.push(`INACTIVE >30 DAYS (${inactive.length})`);
  lines.push(`${pad('Name', 24)}| ${pad('Last seen (UTC)', 18)}| Days inactive`);
  if (inactive.length === 0) lines.push('(none)');
  else for (const r of inactive) {
    const d = daysAgo(r.lastSeen);
    lines.push(`${pad(truncateName(r.name || '?', 24), 24)}| ${pad(fmtDate(r.lastSeen), 18)}| ${d ?? '?'}`);
  }
  lines.push('');
  return lines.join('\n');
}
